spring:
  application:
    name: movieRecsBot

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
          top-p: 0.9


  activate:
    on-profile: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:movie_recs}
    username: ${DB_USERNAME:movie_recs}
    password: ${DB_PASSWORD:movie_recs}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:}
    token: ${TELEGRAM_BOT_TOKEN:}
    webhook-path: ${TELEGRAM_BOT_WEBHOOK_PATH:/tg/webhook}
    webhook-url: ${TELEGRAM_WEBHOOK_URL:}

logging:
  level:
    root: INFO
    com.gnemirko.movieRecsBot: DEBUG
