services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-botdb}
      POSTGRES_USER: ${POSTGRES_USER:-botuser}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-botuser} -d ${POSTGRES_DB:-botdb}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    secrets:
      - postgres_password

  bot:
    build:
      context: ..
      dockerfile: movieRecBot/Dockerfile
    image: movie-recbot:dev
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB:-botdb}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER:-botuser}"
      SPRING_DATASOURCE_PASSWORD: ""
      TELEGRAM_BOT_TOKEN: ""
      OPENAI_API_KEY: ""
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BOT_HTTP_PORT:-8080}:8080"
    restart: unless-stopped
    secrets:
      - open_api_key
      - telegram_bot_token
      - postgres_password

volumes:
  dbdata:

secrets:
  open_api_key:
    file: ./secrets/OPEN_API_KEY
  telegram_bot_token:
    file: ./secrets/TELEGRAM_BOT_TOKEN
  postgres_password:
    file: ./secrets/POSTGRES_PASSWORD
